"""added sender to msg

Revision ID: 6499b5b0bad9
Revises: 
Create Date: 2022-10-17 20:01:37.073169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6499b5b0bad9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_id'), ['id'], unique=False)
        batch_op.create_foreign_key("fk_message_sender", 'message', ['user'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint("fk_message_sender", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_message_id'))

    # ### end Alembic commands ###
